# Generated by Django 4.0.2 on 2022-07-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('cases', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('extract', models.CharField(max_length=200, verbose_name='提取规则')),
                ('vlue', models.CharField(default='', max_length=200, null=True, verbose_name='提取值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.testcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
