# Generated by Django 4.0.2 on 2022-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_testextract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testextract',
            name='case',
        ),
        migrations.AddField(
            model_name='testextract',
            name='case_id',
            field=models.IntegerField(default=0, verbose_name='用例ID'),
        ),
    ]
