# Generated by Django 4.0.2 on 2022-07-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_testextract_case_testextract_case_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testextract',
            old_name='vlue',
            new_name='value',
        ),
    ]
