# Generated by Django 4.0.2 on 2022-03-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
